steps:
  - label: "CUDA with julia {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1: 
          test_args: "--quickfail"
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
    env:
      GROUP: "GPU"
      ADVANCEDVI_TEST_CUDA: "true"
    matrix:
      setup:
        julia:
           - "1.10"

  - label: "Metal with julia {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"

    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    env:
      GROUP: "GPU"
      ADVANCEDVI_TEST_METAL: "true"
    matrix:
      setup:
        julia:
           - "1.10"

  - label: "AMD GPU with Julia {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    timeout_in_minutes: 60
    env:
      JULIA_AMDGPU_CORE_MUST_LOAD: "1"
      JULIA_AMDGPU_HIP_MUST_LOAD: "1"
      JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
      GROUP: "GPU"
      ADVANCEDVI_TEST_AMDGPU: "true"
      JULIA_NUM_THREADS: 4
    matrix:
      setup:
        julia:
           - "1.10"
